### ISSUE TITLE
проблемы

### ISSUE THREAD

**Issue by staskjs** [trikey/node-migrate#1]
- Я бы заменил lodash на sugarjs 
  Почему? Потому что у lodash неудобный синтаксис как в пхп, типа _.map(array, function) и array_map(function, array), это делает невозможным цепочки вызовов. Sugarjs реализует все те же самые методы, которые есть в lodash, но при помощи расширения самих объектов. Рекомендую. Можно писать цепочки вызовов. 
- Ты же стал писать на кофескрипте, чтобы избавиться от скобок. От круглых скобок тоже нужно избавляться в некоторых случаях. Например, когда часть кода у тебя переходит на новую строку, типа 
  
  ``` coffeescript
  _.each(array, (item) ->
     item
  )
  ```
  
  можно заменить на 
  
  ``` coffeescript
   _.each array, (item) ->
       item
  ```
  
  а еще лучше на 

``` coffeescript
array.forEach (item) ->
       item
```
- Заменить `Schema[tableName][key].hasOwnProperty('primary')` на `'primary' of Schema[tableName][key]`
- &&, ||, ! и прочие подобные операторы легко заменяются на английские слова and, or, not. Это считается хорошей практикой и в целом довольно удобно читается
- Использование двойных ковычек без интерполяции не приветствуется. Если нет интерполяции (это запись типа "hello #{variable}", если не помнишь), то лучше использовать одинарные ковычки. Таким образом будешь знать в какой строке есть интерполяция, а в какой нет. У тебя там то одинарные, то двойные, а лучше все таки выработать единый стиль
- Можно забыть про return, если ты не планируешь вернуть значение до того как выполнение дойдет до конца функции. Кофескрипт возвращает последнее значение автоматически, что довольно удобно. Таким образом запись

``` coffeescript
tables = _.map(tableNames, (tableName) ->
        return ->
            return dropTable(tableName)
    )
```

со всеми изменениями превращается в 

``` coffeescript
tables = tableNames.map (tableName) ->
  -> dropTable(tableName)
```
- 

``` coffeescript
action = "nothing"
action = process.argv[3] if process.argv[3]?
```

заменяется в одну строку покрасивее на 

``` coffeescript
action = process.argv[3] or 'nothing'
```

**Comment by trikey** [comment]
переписал код в соответствии с рекомендациями, заюзал sugar
стало лучше
